=== gimi65536/scenario-editor-js/lib/scenario-schema/gimi65536.0.1.0.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "scenario://gimi65536.xyz/schema/0/1/0/",
	"title": "Scenario gimi65536 0.1.0",
	"description": "Scenario exchange format 0.1.0 in JSON",
	"type": "object",
	"properties": {
		"base": {
			"description": "Must be gimi65536",
			"type": "string",
			"enum": [
				"gimi65536"
			]
		},
		"version": {
			"description": "Must be 0.1.0",
			"type": "string",
			"enum": [
				"0.1.0"
			]
		},
		"macro_start": {
			"description": "Start sign of macro",
			"type": "string"
		},
		"macro_end": {
			"description": "Stop sign of macro",
			"type": "string"
		},
		"macro_split": {
			"description": "Split sign in macro",
			"type": "string"
		},
		"title": {
			"description": "Scenario title",
			"type": "string"
		},
		"info": {
			"description": "Scenario info",
			"type": "object"
		},
		"characters": {
			"description": "Character list",
			"type": "object",
			"properties": {
				"order": {
					"description": "Orders of all ID for characters",
					"$ref": "#/$def/order",
					"uniqueItems": true
				},
				"reference": {
					"description": "Actual ID-character mapping",
					"$ref": "#/$def/mapping",
					"additionalProperties": {
						"$ref": "#/$def/character"
					}
				}
			},
			"required": [
				"order",
				"reference"
			]
		},
		"dialogues": {
			"description": "Dialogue list",
			"type": "object",
			"properties": {
				"order": {
					"description": "Orders of all ID for dialogues",
					"$ref": "#/$def/order"
				},
				"reference": {
					"description": "Actual ID-dialogue mapping",
					"$ref": "#/$def/mapping",
					"additionalProperties": {
						"$ref": "#/$def/dialogue"
					}
				}
			},
			"required": [
				"order",
				"reference"
			]
		}
	},
	"required": [
		"base",
		"version",
		"macro_start",
		"macro_end",
		"macro_split",
		"title",
		"info",
		"characters",
		"dialogues"
	],
	"$def": {
		"order": {
			"type": "array",
			"items": {
				"description": "Single ID",
				"type": "string",
				"format": "uuid"
			}
		},
		"mapping": {
			"type": "object",
			"propertyNames": {
				"format": "uuid"
			}
		},
		"character": {
			"description": "Single character",
			"type": "object",
			"properties": {
				"name": {
					"description": "Name of the character",
					"type": "string"
				},
				"color": {
					"description": "Color used in displayer (not restricted to #RGB)",
					"type": "string"
				},
				"abbreviated": {
					"description": "Abbreviation of the character",
					"type": "string"
				},
				"gender": {
					"description": "Gender of the character",
					"type": "string"
				},
				"cast": {
					"description": "Cast of the character",
					"type": "string"
				}
			},
			"additionalProperties": true,
			"required": [
				"name"
			]
		},
		"dialogue": {
			"description": "Single dialogue",
			"type": "object",
			"properties": {
				"components": {
					"$ref": "#/$def/dialogue-component"
				},
				"speaker": {
					"description": "Speaker name displayed",
					"type": "string"
				},
				"speakers_list": {
					"description": "List of the speakers' ID in the character list",
					"type": "array",
					"items": {
						"description": "Single speaker",
						"type": "string",
						"format": "uuid"
					}
				}
			},
			"additionalProperties": true,
			"required": [
				"components",
				"speakers_list"
			]
		},
		"dialogue-component": {
			"description": "Components of the dialogue",
			"type": "array",
			"items": {
				"oneOf": [
					{
						"description": "Single component (plaintext)",
						"type": "string"
					},
					{
						"description": "Single component (macro)",
						"type": "object",
						"properties": {
							"identifier": {
								"description": "Macro identifier",
								"type": "string"
							},
							"children": {
								"description": "Children of the macro",
								"type": "array",
								"items": {
									"$ref": "#/$def/dialogue-component"
								}
							}
						},
						"required": [
							"identifier",
							"children"
						]
					}
				]
			}
		}
	}
}

=== gimi65536/scenario-editor-js/test/NTUCCC 109SS VAD07-gimi65536 0.1.0.json
{"base":"gimi65536","version":"0.1.0","macro_start":"-(","macro_end":")-","macro_split":"/","title":"賽馬娘 Pretty Derby Season 2 第二話","info":{"index":"NTUCCC 109SS VAD07","date":"2021/5/13","image":"uma/main.png","imagelist":"uma/01.png"},"characters":{"order":["8da116c0-f0e8-4a56-86c6-d1799e649640","bbb95a36-24c6-4619-a897-d3e3fd594bc6","d95c6f50-fb53-4f87-a24f-014759967fa7","43059fc6-7d9c-42f7-9975-52eac54e7645","c2cfe124-aaf0-4ceb-ba96-604601044056","4009688f-2ba4-4c46-913b-bd9f0ef550d2","1e4b4b0f-953d-475b-a5bb-7cad04ad6b25","4798857b-2e4a-486f-8054-3325739d68b6","45f664bd-d15d-4ee9-a9ea-49b8e45ff5c8","4321f9cc-dd62-4523-9a20-37ea830acbe0","a0587157-2143-4a49-8f4e-7a8caba93103","c6a845b2-a43e-446a-bc26-d5346d62bd28","c3c79970-c014-4b7f-ad10-475bc5e23960","8f43a181-4d8e-4dcd-b779-79378e7ebc6a","f214a098-0ebf-4ea8-a3b9-a0ca6086806a","d66963cb-78cf-4a4e-b94a-67f1c102dc8d","448243d0-ed6a-4d39-89b4-ddd3b82b643b","4256ede7-d55b-4139-89f4-3b1ff67fe34f","e8f8f419-a43c-48fa-9435-860bdb055ac4","db613b2d-c903-4d42-818f-fce05d2c867b","972df0f9-b2cc-45eb-b187-ef7a30b0790b","b9e8b319-4add-4c87-a224-9e247a2b929b","1e5dcce2-8656-45ee-b2a6-f498f5c70514","60ff399d-42ba-4d72-932d-c2b9ec71279c","e9d92831-08f6-46d6-aaab-acb8f872f25b","8f56b2c4-b638-49d9-aaab-ad577b7c4842","7a5c74ea-bbde-4a81-9971-4173f448894e","b4f8bca1-6341-425d-9bae-60a1bd8372ab","a206903b-31dd-4af9-b0e5-9c65361065d1","ee16a70c-be63-4a8d-b547-5a72a03375fb","3fdd454b-266d-48d3-90a3-b64c63a1b420","d9df3ac7-6ed7-4a3b-8203-ff79fad630fc","df344838-5693-4e45-b110-1bd34d6ef281","ef0ff53a-faf6-4a75-8bfd-34fbdc23d075","7f676bf4-0adc-4a5a-a6cd-f5a72112926b"],"reference":{"8da116c0-f0e8-4a56-86c6-d1799e649640":{"name":"東海帝王","color":"#3376d2","abbreviated":"帝","gender":"♀/公","cast":"Machico"},"bbb95a36-24c6-4619-a897-d3e3fd594bc6":{"name":"目白麥昆","color":"#00b5be","abbreviated":"麥","gender":"♀/公","cast":"大西沙織"},"d95c6f50-fb53-4f87-a24f-014759967fa7":{"name":"訓練師","color":"#f3d874","abbreviated":"訓","gender":"♂","cast":"沖野晃司"},"43059fc6-7d9c-42f7-9975-52eac54e7645":{"name":"特別週","color":"#ee6dcb","abbreviated":"特","gender":"♀/公","cast":"和氣あず未"},"c2cfe124-aaf0-4ceb-ba96-604601044056":{"name":"無聲鈴鹿","color":"#29bd70","abbreviated":"鈴","gender":"♀/公","cast":"高野麻里佳"},"4009688f-2ba4-4c46-913b-bd9f0ef550d2":{"name":"伏特加","color":"#d4c200","abbreviated":"伏","gender":"♀/母","cast":"大橋彩香"},"1e4b4b0f-953d-475b-a5bb-7cad04ad6b25":{"name":"大和赤驥","color":"#4f64d8","abbreviated":"大","gender":"♀/母","cast":"木村千咲"},"4798857b-2e4a-486f-8054-3325739d68b6":{"name":"黃金船","color":"#da3c57","abbreviated":"船","gender":"♀/公","cast":"上田瞳"},"45f664bd-d15d-4ee9-a9ea-49b8e45ff5c8":{"name":"魯鐸象徵","color":"#1c7763","abbreviated":"皇","gender":"♀/公","cast":"田所あずさ"},"4321f9cc-dd62-4523-9a20-37ea830acbe0":{"name":"草上飛","color":"#3a34ac","abbreviated":"草","gender":"♀/公","cast":"前田玲奈"},"a0587157-2143-4a49-8f4e-7a8caba93103":{"name":"北部玄駒","color":"#5a6065","abbreviated":"北","gender":"♀/公","cast":"矢野妃菜喜"},"c6a845b2-a43e-446a-bc26-d5346d62bd28":{"name":"優秀素質","color":"#28a959","abbreviated":"優","gender":"♀/公","cast":"前田佳織里"},"c3c79970-c014-4b7f-ad10-475bc5e23960":{"name":"雙渦輪","color":"#1985d2","abbreviated":"渦","gender":"♀/公","cast":"花井美春"},"8f43a181-4d8e-4dcd-b779-79378e7ebc6a":{"name":"狄杜斯","color":"#49b73f","abbreviated":"狄","gender":"♀/母","cast":"田澤茉純"},"f214a098-0ebf-4ea8-a3b9-a0ca6086806a":{"name":"摩耶重砲","color":"#f57d38","abbreviated":"摩","gender":"♀/公","cast":"星谷美緒"},"d66963cb-78cf-4a4e-b94a-67f1c102dc8d":{"name":"利昂那塔","color":"#2769dc","abbreviated":"利","gender":"♀/公","cast":"青山吉能"},"448243d0-ed6a-4d39-89b4-ddd3b82b643b":{"name":"執事","color":"#b4c1d2","abbreviated":"爺","gender":"♂","cast":"梅津秀行"},"4256ede7-d55b-4139-89f4-3b1ff67fe34f":{"name":"醫生","color":"#a5a29a","abbreviated":"醫","gender":"♂","cast":"宇垣秀成"},"e8f8f419-a43c-48fa-9435-860bdb055ac4":{"name":"美容師","color":"#c398a0","abbreviated":"美","gender":"♀","cast":"美幸キャスリン"},"db613b2d-c903-4d42-818f-fce05d2c867b":{"name":"客人","color":"#614354","abbreviated":"客","gender":"♀","cast":"河上明日香"},"60ff399d-42ba-4d72-932d-c2b9ec71279c":{"name":"路人甲","color":"#aa4b1e","abbreviated":"甲","gender":"♂","cast":"有隅融"},"e9d92831-08f6-46d6-aaab-acb8f872f25b":{"name":"路人乙","color":"#7a3721","abbreviated":"乙","gender":"♂","cast":"上西哲平"},"972df0f9-b2cc-45eb-b187-ef7a30b0790b":{"name":"南坂","color":"#969263","abbreviated":"南","gender":"♂","cast":"古川慎"},"b9e8b319-4add-4c87-a224-9e247a2b929b":{"name":"赤坂美聡","color":"#40979b","abbreviated":"實","gender":"♀","cast":"明坂聡美"},"1e5dcce2-8656-45ee-b2a6-f498f5c70514":{"name":"細江純子","color":"#3e5376","abbreviated":"細","gender":"♀","cast":"細江純子"},"8f56b2c4-b638-49d9-aaab-ad577b7c4842":{"name":"路人丙","color":"#4d485a","abbreviated":"丙","gender":"♂","cast":""},"7a5c74ea-bbde-4a81-9971-4173f448894e":{"name":"路人丁","color":"#5c5357","abbreviated":"丁","gender":"♀","cast":""},"b4f8bca1-6341-425d-9bae-60a1bd8372ab":{"name":"物理治療師","color":"#64466d","abbreviated":"物","gender":"♂","cast":""},"ee16a70c-be63-4a8d-b547-5a72a03375fb":{"name":"廚師","color":"#737262","abbreviated":"廚","gender":"♂","cast":""},"a206903b-31dd-4af9-b0e5-9c65361065d1":{"name":"針灸師","color":"#755848","abbreviated":"針","gender":"♀","cast":""},"3fdd454b-266d-48d3-90a3-b64c63a1b420":{"name":"甜點師","color":"#786579","abbreviated":"甜","gender":"♂","cast":""},"d9df3ac7-6ed7-4a3b-8203-ff79fad630fc":{"name":"主治醫生","color":"#657192","abbreviated":"主","gender":"♂","cast":""},"df344838-5693-4e45-b110-1bd34d6ef281":{"name":"馬娘Ａ","color":"#c33ab3","abbreviated":"Ａ","gender":"♀/公","cast":""},"ef0ff53a-faf6-4a75-8bfd-34fbdc23d075":{"name":"馬娘Ｂ","color":"#d2b22b","abbreviated":"Ｂ","gender":"♀/公","cast":""},"7f676bf4-0adc-4a5a-a6cd-f5a72112926b":{"name":"車掌","color":"#ff0000","abbreviated":"車","gender":"♂","cast":""}}},"dialogues":{"order":[],"reference":{"29e6ce8a-a60c-4de5-92fe-568062ab09a6":{"speaker":"醫","components":["（嗯……）"],"speakers_list":["醫生"]},"55401d89-673d-4b05-9cdc-eee2a991368a":{"speaker":"帝","components":["訓練師太誇張啦，我一點事都沒有的"],"speakers_list":["東海帝王"]},"011a4c58-e9e5-42de-87dd-329f06c3c222":{"speaker":"訓","components":["就怕有個萬一，還是讓醫生看看比較好"],"speakers_list":["訓練師"]},"1882b8aa-6cdb-4a66-8c96-8c35a532c065":{"speaker":"帝","components":["快點結束吧，我還要為了菊花賞鍛鍊呢"],"speakers_list":["東海帝王"]},"2b6b0c87-660d-481b-8d26-9968e3ee7736":{"speaker":"醫","components":["東海帝王"],"speakers_list":["醫生"]},"ab308684-7aa3-4a6d-9e3f-b98cee6d96e3":{"speaker":"帝","components":["什麼？"],"speakers_list":["東海帝王"]},"61129c34-8654-4f45-9b0b-def9fed74518":{"speaker":"醫","components":["折了"],"speakers_list":["醫生"]},"206b06a2-06bd-4c53-b4d5-f59c2c096a3e":{"speaker":"帝、訓","components":["（誒？）"],"speakers_list":["東海帝王","訓練師"]},"4b47a669-ac2d-4157-9f37-d1d63621967a":{"speaker":"醫","components":["是骨折，要回歸比賽得等明年春天了吧"],"speakers_list":["醫生"]},"fa542986-f0a8-4994-847a-47373b17a4bd":{"speaker":"訓","components":["（誒）"],"speakers_list":["訓練師"]},"6fcb29c4-4a3c-4a16-bd19-f400a4210b0a":{"speaker":"帝","components":["（誒！？）"],"speakers_list":["東海帝王"]},"abfb0289-5690-4f9e-8a69-155fb4a25f8a":{"speaker":"醫","components":["請住院吧"],"speakers_list":["醫生"]},"5a0f22d1-52d9-49e7-b2bc-da89b9367ca5":{"speaker":"帝","components":["住院？（上）不要，不要不要不要……（略）"],"speakers_list":["東海帝王"]},"75638bf1-2388-4115-b266-b7aab46c1013":{"speaker":"訓","components":["真的骨折了嗎？"],"speakers_list":["訓練師"]},"776458b6-a2a5-4f48-871b-aa7a5d2e56ee":{"speaker":"醫","components":["骨折了，總之先打上止痛針吧"],"speakers_list":["醫生"]},"afa03666-fbc3-4af2-8f3a-323435685f85":{"speaker":"帝","components":["（誒？）（慘叫）"],"speakers_list":["東海帝王"]},"8f8ae8c4-06ea-4aaa-b1f0-d72668557057":{"speaker":"","components":[{"identifier":"separate","children":[["OP ユメヲカケル"]]}],"speakers_list":[]},"88a1eb28-9a1a-4fe6-9cc7-c06c0e03b75f":{"speaker":"","components":["キミと",{"identifier":"ruby","children":[["夢"],["ゆめ"]]},"をかけるよ"],"speakers_list":[]},"f8d528ab-e739-48f8-a6be-b19bb80f2594":{"speaker":"","components":[{"identifier":"ruby","children":[["何回"],["なんかい"]]},"だって",{"identifier":"ruby","children":[["勝"],["か"]]},"ち",{"identifier":"ruby","children":[["進"],["すす"]]},"め　",{"identifier":"ruby","children":[["勝"],["しょう"]]},{"identifier":"ruby","children":[["利"],["り"]]},"のその",{"identifier":"ruby","children":[["先"],["さき"]]},"へ!"],"speakers_list":[]},"c7190715-e1aa-4ebd-b6c9-602db22eba98":{"speaker":"","components":[],"speakers_list":[]},"63e353cc-4676-4c71-8f6e-97d53ed52f58":{"speaker":"","components":["Sunshine　",{"identifier":"ruby","children":[["前"],["まえ"]]},"を",{"identifier":"ruby","children":[["向"],["む"]]},"けば　Passion　",{"identifier":"ruby","children":[["高"],["たか"]]},{"identifier":"ruby","children":[["鳴"],["な"]]},"るファンファーレ"],"speakers_list":[]},"0daf41b1-6c8c-4b28-9000-9a73c89ba610":{"speaker":"","components":[{"identifier":"ruby","children":[["青空"],["あおぞら"]]},{"identifier":"ruby","children":[["一"],["いっ"]]},{"identifier":"ruby","children":[["直"],["ちょく"]]},{"identifier":"ruby","children":[["線"],["せん"]]},"!(",{"identifier":"ruby","children":[["目指"],["めざ"]]},"せ",{"identifier":"ruby","children":[["一着"],["テッペン"]]},"!)"],"speakers_list":[]},"3643e885-b478-4fd8-9f1f-a29125f76a7c":{"speaker":"","components":["ちょっとヘコむときは　パっと",{"identifier":"ruby","children":[["耳"],["みみ"]]},{"identifier":"ruby","children":[["澄"],["す"]]},"ませてFeel Me!"],"speakers_list":[]},"a4ff916a-475c-4868-8237-73b0c85f31d7":{"speaker":"","components":["その",{"identifier":"ruby","children":[["背"],["せ"]]},{"identifier":"ruby","children":[["中"],["なか"]]},"　",{"identifier":"ruby","children":[["押"],["お"]]},"してたいから"],"speakers_list":[]},"505701f2-f076-4173-a6e0-b9724601ac74":{"speaker":"","components":[],"speakers_list":[]},"be72fa30-ff72-4ae4-b3c7-08222fac9f68":{"speaker":"","components":[{"identifier":"ruby","children":[["気持"],["きも"]]},"ち",{"identifier":"ruby","children":[["一"],["いち"]]},{"identifier":"ruby","children":[["列"],["れつ"]]},"　それぞれに",{"identifier":"ruby","children":[["続"],["つづ"]]},"く",{"identifier":"ruby","children":[["地"],["ち"]]},{"identifier":"ruby","children":[["平"],["へい"]]},{"identifier":"ruby","children":[["線"],["せん"]]},"　",{"identifier":"ruby","children":[[
