=== gimi65536/scenario-editor-js/lib/scenario-schema/gimi65536.0.0.3.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "scenario://gimi65536.0.0.3.schema.json",
	"title": "Scenario gimi65536 0.0.3",
	"description": "Scenario exchange format 0.0.3 in JSON",
	"type": "object",
	"properties": {
		"Base": {"description": "Must be gimi65536",
			"type": "string",
			"enum": [
				"gimi65536"
			]
		},
		"Version": {
			"description": "Must be 0.0.3",
			"type": "string",
			"enum": [
				"0.0.3"
			]
		},
		"MacroStart": {
			"description": "Start sign of macro",
			"type": "string"
		},
		"MacroStop": {
			"description": "Stop sign of macro",
			"type": "string"
		},
		"MacroSplit": {
			"description": "Split sign in macro",
			"type": "string"
		},
		"Title": {
			"description": "Scenario title",
			"type": "string"
		},
		"ScenarioInfo": {
			"description": "Scenario info",
			"type": "object"
		},
		"Character": {
			"description": "Character list (stored in object, however)",
			"type": "object",
			"additionalProperties": {
				"description": "Single character",
				"type": "object",
				"properties": {
					"color": {
						"description": "Color used in displayer (not restricted to #RGB)",
						"type": "string"
					},
					"abbreviated": {
						"description": "Abbreviation of the character",
						"type": "string"
					},
					"gender": {
						"description": "Gender of the character",
						"type": "string"
					},
					"cast": {
						"description": "Cast of the character",
						"type": "string"
					},
					"order": {
						"description": "Order in the virtual character array",
						"type": "integer"
					}
				},
				"required": [
					"color",
					"abbreviated",
					"gender",
					"cast",
					"order"
				]
			}
		},
		"Dialogue": {
			"description": "Dialogue list",
			"type": "array",
			"items": {
				"description": "Single dialogue",
				"type": "object",
				"properties": {
					"Text": {
						"description": "Text",
						"type": "string"
					},
					"Info": {
						"description": "Information of the dialogue",
						"type": "object",
						"properties": {
							"speaker": {
								"description": "Speaker name displayed",
								"type": "string"
							},
							"speaker_list": {
								"description": "List of the speakers in the character list",
								"type": "array",
								"items": {
									"description": "Single speaker",
									"type": "string"
								}
							}
						},
						"required": [
							"speaker",
							"speaker_list"
						]
					}
				},
				"required": [
					"Text",
					"Info"
				]
			}
		}
	},
	"required": [
		"Base",
		"Version",
		"MacroStart",
		"MacroStop",
		"MacroSplit",
		"Title",
		"ScenarioInfo",
		"Character"
	]
}

=== gimi65536/scenario-editor-js/test/NTUCCC 109SS VAD07-gimi65536 0.0.3.json
{
	"Base": "gimi65536",
	"Version": "0.0.3",
	"MacroStart": "-(",
	"MacroStop": ")-",
	"MacroSplit": "/",
	"Title": "賽馬娘 Pretty Derby Season 2 第二話",
	"ScenarioInfo": {
		"index": "NTUCCC 109SS VAD07",
		"date": "2021/5/13",
		"image": "uma/main.png",
		"imagelist": "uma/01.png"
	},
	"Character": {
		"東海帝王": {
			"color": "#3376d2",
			"abbreviated": "帝",
			"gender": "♀/公",
			"cast": "Machico",
			"order": 0
		},
		"目白麥昆": {
			"color": "#00b5be",
			"abbreviated": "麥",
			"gender": "♀/公",
			"cast": "大西沙織",
			"order": 1
		},
		"訓練師": {
			"color": "#f3d874",
			"abbreviated": "訓",
			"gender": "♂",
			"cast": "沖野晃司",
			"order": 2
		},
		"特別週": {
			"color": "#ee6dcb",
			"abbreviated": "特",
			"gender": "♀/公",
			"cast": "和氣あず未",
			"order": 3
		},
		"無聲鈴鹿": {
			"color": "#29bd70",
			"abbreviated": "鈴",
			"gender": "♀/公",
			"cast": "高野麻里佳",
			"order": 4
		},
		"伏特加": {
			"color": "#d4c200",
			"abbreviated": "伏",
			"gender": "♀/母",
			"cast": "大橋彩香",
			"order": 5
		},
		"大和赤驥": {
			"color": "#4f64d8",
			"abbreviated": "大",
			"gender": "♀/母",
			"cast": "木村千咲",
			"order": 6
		},
		"黃金船": {
			"color": "#da3c57",
			"abbreviated": "船",
			"gender": "♀/公",
			"cast": "上田瞳",
			"order": 7
		},
		"魯鐸象徵": {
			"color": "#1c7763",
			"abbreviated": "皇",
			"gender": "♀/公",
			"cast": "田所あずさ",
			"order": 8
		},
		"草上飛": {
			"color": "#3a34ac",
			"abbreviated": "草",
			"gender": "♀/公",
			"cast": "前田玲奈",
			"order": 9
		},
		"北部玄駒": {
			"color": "#5a6065",
			"abbreviated": "北",
			"gender": "♀/公",
			"cast": "矢野妃菜喜",
			"order": 10
		},
		"優秀素質": {
			"color": "#28a959",
			"abbreviated": "優",
			"gender": "♀/公",
			"cast": "前田佳織里",
			"order": 11
		},
		"雙渦輪": {
			"color": "#1985d2",
			"abbreviated": "渦",
			"gender": "♀/公",
			"cast": "花井美春",
			"order": 12
		},
		"狄杜斯": {
			"color": "#49b73f",
			"abbreviated": "狄",
			"gender": "♀/母",
			"cast": "田澤茉純",
			"order": 13
		},
		"摩耶重砲": {
			"color": "#f57d38",
			"abbreviated": "摩",
			"gender": "♀/公",
			"cast": "星谷美緒",
			"order": 14
		},
		"利昂那塔": {
			"color": "#2769dc",
			"abbreviated": "利",
			"gender": "♀/公",
			"cast": "青山吉能",
			"order": 15
		},
		"執事": {
			"color": "#b4c1d2",
			"abbreviated": "爺",
			"gender": "♂",
			"cast": "梅津秀行",
			"order": 16
		},
		"醫生": {
			"color": "#a5a29a",
			"abbreviated": "醫",
			"gender": "♂",
			"cast": "宇垣秀成",
			"order": 17
		},
		"美容師": {
			"color": "#c398a0",
			"abbreviated": "美",
			"gender": "♀",
			"cast": "美幸キャスリン",
			"order": 18
		},
		"客人": {
			"color": "#614354",
			"abbreviated": "客",
			"gender": "♀",
			"cast": "河上明日香",
			"order": 19
		},
		"路人甲": {
			"color": "#aa4b1e",
			"abbreviated": "甲",
			"gender": "♂",
			"cast": "有隅融",
			"order": 23
		},
		"路人乙": {
			"color": "#7a3721",
			"abbreviated": "乙",
			"gender": "♂",
			"cast": "上西哲平",
			"order": 24
		},
		"南坂": {
			"color": "#969263",
			"abbreviated": "南",
			"gender": "♂",
			"cast": "古川慎",
			"order": 20
		},
		"赤坂美聡": {
			"color": "#40979b",
			"abbreviated": "實",
			"gender": "♀",
			"cast": "明坂聡美",
			"order": 21
		},
		"細江純子": {
			"color": "#3e5376",
			"abbreviated": "細",
			"gender": "♀",
			"cast": "細江純子",
			"order": 22
		},
		"路人丙": {
			"color": "#4d485a",
			"abbreviated": "丙",
			"gender": "♂",
			"cast": "",
			"order": 25
		},
		"路人丁": {
			"color": "#5c5357",
			"abbreviated": "丁",
			"gender": "♀",
			"cast": "",
			"order": 26
		},
		"物理治療師": {
			"color": "#64466d",
			"abbreviated": "物",
			"gender": "♂",
			"cast": "",
			"order": 27
		},
		"廚師": {
			"color": "#737262",
			"abbreviated": "廚",
			"gender": "♂",
			"cast": "",
			"order": 29
		},
		"針灸師": {
			"color": "#755848",
			"abbreviated": "針",
			"gender": "♀",
			"cast": "",
			"order": 28
		},
		"甜點師": {
			"color": "#786579",
			"abbreviated": "甜",
			"gender": "♂",
			"cast": "",
			"order": 30
		},
		"主治醫生": {
			"color": "#657192",
			"abbreviated": "主",
			"gender": "♂",
			"cast": "",
			"order": 31
		},
		"馬娘Ａ": {
			"color": "#c33ab3",
			"abbreviated": "Ａ",
			"gender": "♀/公",
			"cast": "",
			"order": 32
		},
		"馬娘Ｂ": {
			"color": "#d2b22b",
			"abbreviated": "Ｂ",
			"gender": "♀/公",
			"cast": "",
			"order": 33
		},
		"車掌": {
			"color": "#ff0000",
			"abbreviated": "車",
			"gender": "♂",
			"cast": "",
			"order": 34
		}
	},
	"Dialogue": [
		{
			"Text": "（嗯……）",
			"Info": {
				"speaker": "醫",
				"speaker_list": [
					"醫生"
				]
			}
		},
		{
			"Text": "訓練師太誇張啦，我一點事都沒有的",
			"Info": {
				"speaker": "帝",
				"speaker_list": [
					"東海帝王"
				]
			}
		},
		{
			"Text": "就怕有個萬一，還是讓醫生看看比較好",
			"Info": {
				"speaker": "訓",
				"speaker_list": [
					"訓練師"
				]
			}
		},
		{
			"Text": "快點結束吧，我還要為了菊花賞鍛鍊呢",
			"Info": {
				"speaker": "帝",
				"speaker_list": [
					"東海帝王"
				]
			}
		},
		{
			"Text": "東海帝王",
			"Info": {
				"speaker": "醫",
				"speaker_list": [
					"醫生"
				]
			}
		},
		{
			"Text": "什麼？",
			"Info": {
				"speaker": "帝",
				"speaker_list": [
					"東海帝王"
				]
			}
		},
		{
			"Text": "折了",
			"Info": {
				"speaker": "醫",
				"speaker_list": [
					"醫生"
				]
			}
		},
		{
			"Text": "（誒？）",
			"Info": {
				"speaker": "帝、訓",
				"speaker_list": [
					"東海帝王",
					"訓練師"
				]
			}
		},
		{
			"Text": "是骨折，要回歸比賽得等明年春天了吧",
			"Info": {
				"speaker": "醫",
				"speaker_list": [
					"醫生"
				]
			}
		},
		{
			"Text": "（誒）",
			"Info": {
				"speaker": "訓",
				"speaker_list": [
					"訓練師"
				]
			}
		},
		{
			"Text": "（誒！？）",
			"Info": {
				"speaker": "帝",
				"speaker_list": [
					"東海帝王"
				]
			}
		},
		{
			"Text": "請住院吧",
			"Info": {
				"speaker": "醫",
				"speaker_list": [
					"醫生"
				]
			}
		},
		{
			"Text": "住院？（上）不要，不要不要不要……（略）",
			"Info": {
				"speaker": "帝",
				"speaker_list": [
					"東海帝王"
				]
			}
		},
		{
			"Text": "真的骨折了嗎？",
			"Info": {
				"speaker": "訓",
				"speaker_list": [
					"訓練師"
				]
			}
		},
		{
			"Text": "骨折了，總之先打上止痛針吧",
			"Info": {
				"speaker": "醫",
				"speaker_list": [
					"醫生"
				]
			}
		},
		{
			"Text": "（誒？）（慘叫）",
			"Info": {
				"speaker": "帝",
				"speaker_list": [
					"東海帝王"
				]
			}
		},
		{
			"Text": "-( separate/OP ユメヲカケル )-",
			"Info": {
				"speaker": "",
				"speaker_list": []
			}
		},
		{
			"Text": "キミと-( ruby/夢/ゆめ )-をかけるよ",
			"Info": {
				"speaker": "",
				"speaker_list": []
			}
		},
		{
			"Text": "-( ruby/何回/なんかい )-だって-( ruby/勝/か )-ち-( ruby/進/すす )-め　-( ruby/勝/しょう )--( ruby/利/り )-のその-( ruby/先/さき )-へ!",
			"Info": {
				"speaker": "",
				"speaker_list": []
			}
		},
		{
			"Text": "",
			"Info": {
				"speaker": "",
				"speaker_list": []
			}
		},
		{
			"Text": "Sunshine　-( ruby/前/まえ )-を-( ruby/向/む )-けば　Passion　-( ruby/高/たか )--( ruby/鳴/な )-るファンファーレ",
			"Info": {
				"speaker": "",
				"speaker_list": []
			}
		},
		{
			"Text": "-( ruby/青空/あおぞら )--( ruby/一/いっ )--( ruby/直/ちょく )--( ruby/線/せん )-!(-( ruby/目指/めざ )-せ-( ruby/一着/テッペン )-!)",
			"Info": {
				"speaker": "",
				"speaker_list": []
			}
		},
		{
			"Text": "ちょっとヘコむときは　パっと-( ruby/耳/みみ )--( ruby/澄/す )-ませてFeel Me!",
			"Info": {
				"speaker": "",
				"speaker_list": []
			}
		},
		{
			"Text": "その-( ruby/背/せ )--( ruby/中/なか )-　-( ruby/押/お )-してたいから",
			"Info": {
				"speaker": "",
				"speaker_list": []
			}
		},
		{
			"Text": "",
			"Info": {
				"speaker": "",
				"speaker_list": []
			}
		},
		{
			"Text": "-( ruby/気持/きも )-ち-( ruby/一/いち )--( ruby/列/れつ )-　それぞれに-( ruby/続/つづ )-く-( ruby/地/ち )--( ruby/平/へい )--( ruby/線/せん )-　-( ruby/蹴/け )-って",
			"Info": {
				"speaker": "",
				"speaker_list": []
			}
		},
		{
			"Text": "(No More!)-( ruby/迷/まよ )-わないで",
			"Info": {
				"speaker": "",
				"speaker_list": []
			}
		},
		{
			"Text": "(Let's Go!)-( ruby/止/と )-まらず-( ruby/行/い )-こう!",
			"Info": {
				"speaker": "",
				"speaker_list": []
			}
		},
		{
			"Text": "",
			"Info": {
				"speaker": "",
				"speaker_list": []
			}
		},
		{
			"Text": "キミと-( ruby/夢/ゆめ )-をかけるよ",
			"Info": {
				"speaker": "",
				"speaker_list": []
			}
		},
		{
			"Text": "-( ruby/何回/なんかい )-だって　-( ruby/巻/ま )-き-( ruby/起/お )-こせスパート",
			"Info": {
				"speaker": "",
				"speaker_list": []
			}
		},
		{
			"Text": "-( ruby/諦/あきら )-めないで　I Believe!",
			"Info": {
				"speaker": "",
				"speaker_list": []
			}
		},
		{
			"Text": "いつか-( ruby/決/き )-めたゴールに",
			"Info": {
				"speaker": "",
				"speaker_list": []
			}
		},
		{
			"Text": "Try!-( ruby/届/とど )-け　-( ruby/全速/ぜんそく )-で",
			"Info": {
				"speaker": "",
				"speaker_list": []
			}
		},
		{
			"Text": "-( ruby/走/はし )-りまくろう　Never Give Up",
			"Info": {
				"speaker": "",
				"speaker_list": []
			}
		},
		{
			"Text": "-( ruby/風/かぜ )-も-( ruby/音/おと )-もヒカリも",
			"Info": {
				"speaker": "",
				"speaker_list": []
			}
		},
		{
			"Text": "-( ruby/追/お )-い-( ruby/越/こ )-しちゃって　-( ruby/誰/だれ )-も-( ruby/知/し )-らない-( ruby/明日/あした )-へ-( ruby/進/すす )-め!",
			"Info": {
				"speaker": "",
				"speaker_list": []
			}
		},
		{
			"Text": "(ほら)キミと-( ruby/夢/ゆめ )-を-( ruby/重/かさ )-ねてる",
			"Info": {
				"speaker": "",
				"speaker_list": []
			}
		},
		{
			"Text": "(ほら)その-( ruby/姿/すがた )-この-( ruby/瞳/ひとみ )-　-( ruby/映/うつ )-ってるから",
			"Info": {
				"speaker": "",
				"speaker_list": []
			}
		},
		{
			"Text": "-( separate )-",
			"Info": {
				"speaker": "",
				"speaker_list": []
			}
		},
		{
			"Text": "妳剛才說什麼？",
			"Info": {
				"speaker": "訓",
				"speaker_list": [
					"訓練師"
				]
			}
		},
		{
			"Text": "我說要參加菊花賞",
			"Info": {
				"speaker": "帝",
				"speaker_list": [
					"東海帝王"
				]
			}
		},
		{
			"Text": "就算要參加，可是妳……",
			"Info": {
				"speaker": "訓",
				"speaker_list": [
					"訓練師"
				]
			}
		},
		{
			"Text": "六個月才能痊癒？明年春天復出？那又怎麼樣，你以為對方這麼說我就能放棄菊花賞嗎？",
			"Info": {
				"speaker": "帝",
				"speaker_list": [
					"東海帝王"
				]
			}
		},
		{
			"Text": "不會的",
			"Info": {
				"speaker": "訓",
				"speaker_list": [
					"訓練師"
				]
			}
		},
		{
			"Text": "我絕對要參加，然後絕對要贏",
			"Info": {
				"speaker": "帝",
				"speaker_list": [
					"東海帝王"
				]
			}
		},
		{
			"Text": "……沒辦法，想個計劃吧",
			"Info": {
				"speaker": "訓",
				"speaker_list": [
					"訓練師"
